export const BaseUrl = "http://192.168.1.82:3010/api/"

export const uploadapi = "upload"
export const userloginapi = "user/login"
export const usersapi = "user"
export const truckapi = "truck"
export const quotationapi = "quotation"
export const jobapi = "job"
export const vehicleTypeapi = "vehicle-type"
export const financeapi = "finance"