export const loginPath = "login";
export const basePath = "/";
// export const managerPath = "managers";
// export const ordersPath = "orders";
// export const pricingPlanPath = "pricing-plan";
// export const specializationPath = "specialization";
// export const doctorsPath = "doctor";
// export const paymentsPath = "payments";
export const settingsPath = "settings";
export const notificationPath = "notification";
export const quotationPath = "quotation"
export const jobsPath = "jobs"
export const financePath = "finance"
export const truckPath = "trucks"
export const driversPath = "drivers"
